import type { Residue, Company, ImpactMetric } from './types';

export const mockCompanies: Company[] = [
  {
    id: 'comp-1',
    name: 'Almazara EcoOliva',
    type: 'GENERATOR',
    description: 'Productora de aceite de oliva con residuos de alperujo',
    city: 'Jaén',
    country: 'España',
    verificationStatus: 'VERIFIED',
    lat: 37.7796,
    lng: -3.7859,
  },
  {
    id: 'comp-2',
    name: 'AgroFresh Foods',
    type: 'GENERATOR',
    description: 'Procesadora de alimentos frescos',
    city: 'Murcia',
    country: 'España',
    verificationStatus: 'PENDING',
    lat: 37.9922,
    lng: -1.1307,
  },
  {
    id: 'comp-3',
    name: 'BioGas Energía',
    type: 'TRANSFORMER',
    description: 'Producción de biogás a partir de residuos orgánicos',
    city: 'Valencia',
    country: 'España',
    verificationStatus: 'VERIFIED',
    lat: 39.4699,
    lng: -0.3763,
  },
];

export const mockResidues: Residue[] = [
  {
    id: 'res-1',
    companyId: 'comp-1',
    company: mockCompanies[0],
    type: 'Alperujo',
    category: 'AGRO',
    quantity: 50.5,
    unit: 'TON',
    availabilityDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    pricePerUnit: 15.0,
    locationLat: 37.7796,
    locationLng: -3.7859,
    status: 'ACTIVE',
    photos: ['https://picsum.photos/seed/res1/600/400'],
    description: 'Residuo de la extracción de aceite de oliva, rico en materia orgánica. Ideal para compostaje y producción de biomasa.',
    moisturePct: 65.0,
    contaminants: 'Huesos de aceituna',
  },
  {
    id: 'res-2',
    companyId: 'comp-2',
    company: mockCompanies[1],
    type: 'Cáscaras de frutas',
    category: 'FOOD',
    quantity: 10,
    unit: 'TON',
    availabilityDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    pricePerUnit: 5.0,
    locationLat: 37.9922,
    locationLng: -1.1307,
    status: 'ACTIVE',
    photos: ['https://picsum.photos/seed/res2/600/400'],
    description: 'Mezcla de cáscaras de naranja, limón y manzana provenientes de nuestra planta de zumos. Alto contenido en azúcares.',
    moisturePct: 80.0,
    contaminants: 'Ninguno',
  },
  {
    id: 'res-3',
    companyId: 'comp-1',
    company: mockCompanies[0],
    type: 'Hoja de olivo',
    category: 'BIOMASS',
    quantity: 15,
    unit: 'TON',
    availabilityDate: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString(),
    pricePerUnit: 10.0,
    locationLat: 37.7796,
    locationLng: -3.7859,
    status: 'ACTIVE',
    photos: ['https://picsum.photos/seed/res3/600/400'],
    description: 'Hoja de olivo y ramas finas procedentes de la poda anual. Secas y listas para su uso como biomasa.',
    moisturePct: 20.0,
    contaminants: 'Ramas pequeñas',
  },
  {
    id: 'res-4',
    companyId: 'comp-2',
    company: mockCompanies[1],
    type: 'Restos de verduras',
    category: 'FOOD',
    quantity: 8,
    unit: 'TON',
    availabilityDate: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000).toISOString(),
    pricePerUnit: 3.0,
    locationLat: 37.9922,
    locationLng: -1.1307,
    status: 'ACTIVE',
    photos: ['https://picsum.photos/seed/res4/600/400'],
    description: 'Restos de lechuga, tomate y pepino no aptos para la venta. Ideales para alimentación animal o compostaje.',
    moisturePct: 85.0,
    contaminants: 'Tierra mínima',
  },
];

const MESES = ['Ene', 'Feb', 'Mar', 'Abr', 'May', 'Jun', 'Jul', 'Ago', 'Sep', 'Oct', 'Nov', 'Dic'];

export const mockImpactMetrics: ImpactMetric[] = [
  { label: MESES[0], co2Avoided: 250, wasteDiverted: 500, savings: 750 },
  { label: MESES[1], co2Avoided: 320, wasteDiverted: 640, savings: 960 },
  { label: MESES[2], co2Avoided: 450, wasteDiverted: 900, savings: 1350 },
  { label: MESES[3], co2Avoided: 400, wasteDiverted: 800, savings: 1200 },
  { label: MESES[4], co2Avoided: 550, wasteDiverted: 1100, savings: 1650 },
  { label: MESES[5], co2Avoided: 600, wasteDiverted: 1200, savings: 1800 },
];
