import type { Residue, Company, ImpactMetric } from './types';

export const mockCompanies: Company[] = [
  {
    id: 'comp-1',
    name: 'Almazara EcoOliva',
    type: 'GENERATOR',
    description: 'Productora de aceite de oliva con residuos de alperujo',
    city: 'Jaén',
    country: 'España',
    verificationStatus: 'VERIFIED',
    lat: 37.7796,
    lng: -3.7859,
  },
  {
    id: 'comp-2',
    name: 'AgroFresh Foods',
    type: 'GENERATOR',
    description: 'Procesadora de alimentos frescos',
    city: 'Murcia',
    country: 'España',
    verificationStatus: 'PENDING',
    lat: 37.9922,
    lng: -1.1307,
  },
  {
    id: 'comp-3',
    name: 'BioGas Energía',
    type: 'TRANSFORMER',
    description: 'Producción de biogás a partir de residuos orgánicos',
    city: 'Valencia',
    country: 'España',
    verificationStatus: 'VERIFIED',
    lat: 39.4699,
    lng: -0.3763,
  },
   {
    id: 'comp-4',
    name: 'Viñedos del Sol',
    type: 'GENERATOR',
    description: 'Bodega productora de vino con residuos de orujo de uva.',
    city: 'La Rioja',
    country: 'España',
    verificationStatus: 'VERIFIED',
    lat: 42.4653,
    lng: -2.4485,
  },
  {
    id: 'comp-5',
    name: 'Maderas Sostenibles S.L.',
    type: 'GENERATOR',
    description: 'Aserradero y procesador de madera.',
    city: 'Lugo',
    country: 'España',
    verificationStatus: 'PENDING',
    lat: 43.0120,
    lng: -7.5560,
  },
];

export let mockResidues: Residue[] = [
  {
    id: 'res-1',
    companyId: 'comp-1',
    company: mockCompanies[0],
    type: 'Alperujo',
    category: 'AGRO',
    quantity: 50.5,
    unit: 'TON',
    availabilityDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    pricePerUnit: 15.0,
    locationLat: 37.7796,
    locationLng: -3.7859,
    status: 'ACTIVE',
    photos: ['https://picsum.photos/seed/alperujo/600/400'],
    description: 'Residuo de la extracción de aceite de oliva, rico en materia orgánica. Ideal para compostaje y producción de biomasa.',
    moisturePct: 65.0,
    contaminants: 'Huesos de aceituna',
  },
  {
    id: 'res-2',
    companyId: 'comp-2',
    company: mockCompanies[1],
    type: 'Cáscaras de cítricos',
    category: 'FOOD',
    quantity: 10,
    unit: 'TON',
    availabilityDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    pricePerUnit: 5.0,
    locationLat: 37.9922,
    locationLng: -1.1307,
    status: 'ACTIVE',
    photos: ['https://picsum.photos/seed/citricos/600/400'],
    description: 'Mezcla de cáscaras de naranja y limón provenientes de nuestra planta de zumos. Alto contenido en azúcares.',
    moisturePct: 80.0,
    contaminants: 'Ninguno',
  },
  {
    id: 'res-3',
    companyId: 'comp-1',
    company: mockCompanies[0],
    type: 'Hoja de olivo',
    category: 'BIOMASS',
    quantity: 15,
    unit: 'TON',
    availabilityDate: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString(),
    pricePerUnit: 10.0,
    locationLat: 37.7796,
    locationLng: -3.7859,
    status: 'ACTIVE',
    photos: ['https://picsum.photos/seed/hojaolivo/600/400'],
    description: 'Hoja de olivo y ramas finas procedentes de la poda anual. Secas y listas para su uso como biomasa.',
    moisturePct: 20.0,
    contaminants: 'Ramas pequeñas',
  },
  {
    id: 'res-4',
    companyId: 'comp-4',
    company: mockCompanies[3],
    type: 'Orujo de uva',
    category: 'AGRO',
    quantity: 30,
    unit: 'TON',
    availabilityDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    pricePerUnit: 18.0,
    locationLat: 42.4653,
    locationLng: -2.4485,
    status: 'ACTIVE',
    photos: ['https://picsum.photos/seed/orujo/600/400'],
    description: 'Residuo de la producción de vino, compuesto por pieles, pulpa y semillas de uva. Apto para destilerías y compost.',
    moisturePct: 55.0,
    contaminants: 'Raspón (escobajo)',
  },
  {
    id: 'res-5',
    companyId: 'comp-5',
    company: mockCompanies[4],
    type: 'Serrín de pino',
    category: 'BIOMASS',
    quantity: 25,
    unit: 'TON',
    availabilityDate: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
    pricePerUnit: 25.0,
    locationLat: 43.0120,
    locationLng: -7.5560,
    status: 'ACTIVE',
    photos: ['https://picsum.photos/seed/serrin/600/400'],
    description: 'Serrín fino y limpio procedente del corte de madera de pino. Ideal para la fabricación de pellets y tableros de aglomerado.',
    moisturePct: 15.0,
    contaminants: 'Ninguno',
  },
  {
    id: 'res-6',
    companyId: 'comp-2',
    company: mockCompanies[1],
    type: 'Bagazo de cerveza',
    category: 'FOOD',
    quantity: 8,
    unit: 'TON',
    availabilityDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    pricePerUnit: 22.0,
    locationLat: 37.9922,
    locationLng: -1.1307,
    status: 'ACTIVE',
    photos: ['https://picsum.photos/seed/bagazo/600/400'],
    description: 'Residuo sólido de la fabricación de cerveza, rico en proteínas y fibra. Excelente para alimentación animal.',
    moisturePct: 75.0,
    contaminants: 'Ninguno',
  },
  {
    id: 'res-7',
    companyId: 'comp-1',
    company: mockCompanies[0],
    type: 'Poda de olivo',
    category: 'BIOMASS',
    quantity: 40,
    unit: 'TON',
    availabilityDate: new Date().toISOString(),
    pricePerUnit: 12.0,
    locationLat: 37.7796,
    locationLng: -3.7859,
    status: 'RESERVED',
    photos: ['https://picsum.photos/seed/podaolivo/600/400'],
    description: 'Ramas de olivo trituradas. Biomasa de alta calidad para calderas industriales.',
    moisturePct: 35.0,
    contaminants: 'Ninguno',
  },
  {
    id: 'res-8',
    companyId: 'comp-5',
    company: mockCompanies[4],
    type: 'Corteza de árbol',
    category: 'BIOMASS',
    quantity: 18,
    unit: 'TON',
    availabilityDate: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000).toISOString(),
    pricePerUnit: 8.0,
    locationLat: 43.0120,
    locationLng: -7.5560,
    status: 'ACTIVE',
    photos: ['https://picsum.photos/seed/corteza/600/400'],
    description: 'Corteza procedente del descortezado de troncos. Usos en jardinería (mulching) y como combustible.',
    moisturePct: 45.0,
    contaminants: 'Tierra',
  },
    {
    id: 'res-9',
    companyId: 'comp-3',
    company: mockCompanies[2],
    type: 'Paja de cereal',
    category: 'AGRO',
    quantity: 150,
    unit: 'TON',
    availabilityDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
    pricePerUnit: 40.0,
    locationLat: 39.4699,
    locationLng: -0.3763,
    status: 'ACTIVE',
    photos: ['https://picsum.photos/seed/paja/600/400'],
    description: 'Paja de trigo y cebada post-cosecha. Apta para alimentación de ganado, camas de animales o producción de energía.',
    moisturePct: 12.0,
    contaminants: 'Ninguno',
  },
  {
    id: 'res-10',
    companyId: 'comp-2',
    company: mockCompanies[1],
    type: 'Suero lácteo',
    category: 'FOOD',
    quantity: 20,
    unit: 'TON',
    availabilityDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
    pricePerUnit: 3.0,
    locationLat: 37.9922,
    locationLng: -1.1307,
    status: 'CLOSED',
    photos: ['https://picsum.photos/seed/suero/600/400'],
    description: 'Subproducto líquido de la fabricación de queso. Rico en lactosa, proteínas y minerales. Potencial para la industria alimentaria y farmacéutica.',
    moisturePct: 95.0,
    contaminants: 'Ninguno',
  },
];

const MESES = ['Ene', 'Feb', 'Mar', 'Abr', 'May', 'Jun', 'Jul', 'Ago', 'Sep', 'Oct', 'Nov', 'Dic'];

export const mockImpactMetrics: ImpactMetric[] = [
  { label: MESES[0], co2Avoided: 250, wasteDiverted: 500, savings: 750 },
  { label: MESES[1], co2Avoided: 320, wasteDiverted: 640, savings: 960 },
  { label: MESES[2], co2Avoided: 450, wasteDiverted: 900, savings: 1350 },
  { label: MESES[3], co2Avoided: 400, wasteDiverted: 800, savings: 1200 },
  { label: MESES[4], co2Avoided: 550, wasteDiverted: 1100, savings: 1650 },
  { label: MESES[5], co2Avoided: 600, wasteDiverted: 1200, savings: 1800 },
];
